### PR TITLE
[fuzzydir] add `excluded_dir` options to ignore specified paths

### LINKED ISSUE #9: a parameter cannot be found that matches parameter name 'Directory'.
Using the latest update fuzzydir https://github.com/sibwaf/mpv-scripts/commit/91b147ff34bd743caa28e6cfc6f3ff430cbd0e81
Watching YouTube on mpv.

### PR DESCRIPTION
**Pull request by dyphire**
The successor to #2. I think it's time to implement it.
Close https://github.com/sibwaf/mpv-scripts/issues/9

### CODE REVIEW

**Comment by sibwaf** [comment]
About #9: let's not jump the gun just yet, we don't have enough information about what's wrong here. Based on the name of the issue it looks like the `-Directory` parameter for some reason doesn't work, though in theory it should with PowerShell 3+. I do have a suspicion that we don't quote the path properly (it's kinda complicated with PowerShell), but that needs further research.

I should also probably hide those horrendous error messages so people don't get so scared, I guess. It's completely fine in the cases it fails to scan some paths (happens, for example, if a directory doesn't exist) - this particular path just gets ignored and everything continues working as expected. Thus, we don't have a reason to add a crutch for completely skipping all protocols. If we can't scan paths for the opened file - well, just silently fail, it's not a problem.

---

As for the path exclusion - yeah, it's a good feature to have, but configuring it like this rubs me the wrong way. I think it would be better to add the exclusions to mpv's config directly, something like this (notice the exclamation sign; also - not the final syntax):
```
sub-file-paths=**;!audio;!Z:\**
```

This way all the configuration you care about is conveniently kept in one place with consistent syntax. The two properties that are configured in the script directly at the moment are, to be honest, just constants which no one should ever touch without a good reason. Thus, I don't really consider those as configuration.

This is also connected to #4, which is still not completely implemented as there is no way to enforce scanning some directories - I'm thinking about something similar, but I don't really have any good ideas for the syntax for now.

**Comment by Obegg** [comment]
Tested this PR https://raw.githubusercontent.com/sibwaf/mpv-scripts/788dcc5fa15901045aacaafb7c4776924cb90349/fuzzydir.lua
No error message

**Comment by dyphire** [comment]
> About #9: let's not jump the gun just yet, we don't have enough information about what's wrong here. Based on the name of the issue it looks like the `-Directory` parameter for some reason doesn't work, though in theory it should with PowerShell 3+. I do have a suspicion that we don't quote the path properly (it's kinda complicated with PowerShell), but that needs further research.
> I should also probably hide those horrendous error messages so people don't get so scared, I guess. It's completely fine in the cases it fails to scan some paths (happens, for example, if a directory doesn't exist) - this particular path just gets ignored and everything continues working as expected. Thus, we don't have a reason to add a crutch for completely skipping all protocols. If we can't scan paths for the opened file - well, just silently fail, it's not a problem.

The syntax of the powershell command is correct. The error was reported only because the network protocol is not a directory, which is in line with expectations.
image
In fact, as mentioned in the commit, the script has never worked for the protocol content because `utils.readdir(path, "dirs")` .
Commit https://github.com/sibwaf/mpv-scripts/commit/dca7f616be93bbef0dce39062ae38f564d8830be introduced this bug. This is a bug fix, not a functional break.
When it is clear that the script will not work for the protocol content, we should actively ignore it and stop working instead of allowing the script to continue executing and then silently fail.

> As for the path exclusion - yeah, it's a good feature to have, but configuring it like this rubs me the wrong way. I think it would be better to add the exclusions to mpv's config directly, something like this (notice the exclamation sign; also - not the final syntax):
> 
> ```
> sub-file-paths=**;!audio;!Z:\**
> ```
> 
> This way all the configuration you care about is conveniently kept in one place with consistent syntax. The two properties that are configured in the script directly at the moment are, to be honest, just constants which no one should ever touch without a good reason. Thus, I don't really consider those as configuration.

I don't quite agree with this because I don't like scripts intruding too much into configuration files of mpv.conf. This approach is too hacker. By the way, the method you proposed will perform related operations in the `explore` function. In my opinion, this is just like the protocol content, which is unnecessary script operations because they all perform redundant operations.

It is much cleaner to implement it in the script's configuration file of `script-opts/fuzzydir.conf`, which is also the recommended usage of mpv

**Comment by sibwaf** [comment]
> The syntax of the powershell command is correct. The error was reported only because the network protocol is not a directory, which is in line with expectations.

Well, can't say that it's what I expected by the error message "unknown parameter -Directory". If the path doesn't exist it should be "PathNotFound" or something, not an "invalid parameter" for an unrelated parameter.

Whatever, not really important.

> This is a bug fix, not a functional break.

This is indeed a functional break to just cut off ALL protocols. What if some of the protocols work? Or will start to work with the next mpv update? We'll have to make exceptions for the ones that work, and then the script will break on older mpv versions. This will be a maintenance hell.

The bug is not functional, it's purely visual. You can try adding `testtesttest/**` to your `sub-file-paths` and opening something. You will get an error as the script tries to scan a directory that doesn't exist, but the subtitles will still be properly loaded as the error is ignored.

Then you can add this to the script after `capture_stdout = true`:
```lua
capture_stderr = true,
```

The error will disappear from mpv's log, even though we did nothing to "fix" it. We just hide the output which wasn't supposed to be shown in the first place (and on Linux it's not there by the way, mpv probably forks the process and doesn't connect the stdout/stderr to the main one; though that's just a guess, a bit too lazy to check the source code for that).

> I don't like scripts intruding too much into configuration files of mpv.conf

The script already uses `*-paths` properties in mpv.conf and no one is complaining about this. We're not going to intrude on any other properties and just add more functionality to the same ones. And you certainly need to have inclusions before your eyes for reference when configuring the exclusions.

I also tried the options-way when I was implementing #4. In my opinion, this wasn't convenient to use - thus I skipped on the "force-scan" functionality and then got this idea a bit later. It just doesn't make sense to me to have interconnected configurations being not even in different properties, but in different files.

I can make a vote for this if I didn't manage to convince you, though I'm not sure we'll get enough votes for any conclusive results.

**Comment by dyphire** [comment]
> > This is a bug fix, not a functional break.
> 
> This is indeed a functional break to just cut off ALL protocols. What if some of the protocols work? Or will start to work with the next mpv update? We'll have to make exceptions for the ones that work, and then the script will break on older mpv versions. This will be a maintenance hell.

As long as the mechanism of `utils.readdir(path, "dirs")` does not change, no protocols content will take effect. mpv developers don't seem willing to change this either: https://github.com/mpv-player/mpv/issues/11438

> The bug is not functional, it's purely visual. You can try adding `testtesttest/**` to your `sub-file-paths` and opening something. You will get an error as the script tries to scan a directory that doesn't exist, but the subtitles will still be properly loaded as the error is ignored.
> 
> Then you can add this to the script after `capture_stdout = true`:
> 
> ```lua
> capture_stderr = true,
> ```
>
> The error will disappear from mpv's log, even though we did nothing to "fix" it. We just hide the output which wasn't supposed to be shown in the first place (and on Linux it's not there by the way, mpv probably forks the process and doesn't connect the stdout/stderr to the main one; though that's just a guess, a bit too lazy to check the source code for that).

Yes, this can suppress log output and silently fail. This is a better method.

> > I don't like scripts intruding too much into configuration files of mpv.conf
> 
> The script already uses `*-paths` properties in mpv.conf and no one is complaining about this. We're not going to intrude on any other properties and just add more functionality to the same ones. And you certainly need to have inclusions before your eyes for reference when configuring the exclusions.
> 
> I also tried the options-way when I was implementing #4. In my opinion, this wasn't convenient to use - thus I skipped on the "force-scan" functionality and then got this idea a bit later. It just doesn't make sense to me to have interconnected configurations being not even in different properties, but in different files.
> 
> I can make a vote for this if I didn't manage to convince you, though I'm not sure we'll get enough votes for any conclusive results.

We cannot agree on the implementation method, and I am not willing to further invade mpv.conf because I will only use it in the script configuration file.

**Pull request closed without merging**
